### ISSUE TITLE
error message: "You do not have a ROM image installed for Model 1"

### ISSUE THREAD

**Issue by DanStach** [RetroPie/sdltrs#4]
I have loaded a few TRS-80 after installing the exp package sdltrs (RetroPie on a RPI Zero W). all roms result in the error message "You do not have a ROM image installed for Model 1"

not sure what this means or how to troubleshoot this

**Comment by HerbFargus** [comment]
The error means what it says.

**Comment by SireInsectus** [comment]
@HerbFargus How does one install a ROM image for "Model 1"?
